package it.polimi.ingsw.controller.command;

public enum GameCommandValues {
    MOTHERNATURE, MAP, ISLANDARRAY, PLAYERARRAY, CLOUD, CLOUDARRAY, ENTRANCE, DININGROOM, GLOBALPROFESSORTABLE, COINPOOL, CHARACTERCARDARRAY
}
